softprops/action-gh-release

CHANGELOG.md, README.md, __tests__/util.test.ts, action.yml, lib/util.js, src/util.ts
=> add support for multi-line delimited assets

CHANGELOG.md, README.md, __tests__/util.test.ts, action.yml, lib/github.js, lib/util.js, src/github.ts, src/util.ts
=> add support for prereleases 

action.yml, lib/main.js, src/main.ts
This will allow subsequent actions to get access to the HTML URL for the release created with this. Handy for composing multiple actions together that are related to the release.
In my case I wanted to get the  URL into a slack message posted to the team when a release is published.
The output can be referenced by using the `steps.release.ouput.url` in
the workflow yaml:
- name: Release
id: release
uses: softprops/action-gh-release@v1
with:
name: "My Release"
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- name: Slack
uses: csexton/slack-message-action@v1
with:
message: New release posted at ${{ steps.release.outputs.url}}
=> Add the release HTML URL to outputs

README.md
As of 2019-11-13 GitHub Actions is out of beta!
See: https://github.blog/2019-11-13-universe-day-one/#github-actions
=> chore: remove note about github action beta

lib/github.js, src/github.ts
Whenever supplying a non-existing file as `body_path`, the release method will retry indefinitely due the error thrown by `releaseBody`.
Catching errors only within `createRelease` call would correctly throw the error and terminate the script.
=> Only catch github API error

.github/workflows/main.yml, lib/github.js, src/github.ts, src/main.ts
Hi!
I have a use case where I need to update existing release body with output from multiple workflows, so I did few modifications and implemented that functionality. Do you think this is a good way to do it, and if it is, would you accept this PR? :)
Cheers!
=> Ability to update existing release body

README.md
Sorry, I made a mistake in #39.
It should be `github.ref` or `GITHUB_REF`.
=> Fix mistake in #39

package.json
On Windows, single quotes cannot be used for quoting command line.
Use double quotes instead.
=> Make "npm run fmt(check)" work on Windows

CONTRIBUTING.md, README.md
I was using the repository and noted some spelling mistakes. This PR aims to fix them. Particularly, in the `README.md` and `CONTRIBUTING.md` files.
'reuse' instead of 'resuse':
```diff
-as it maximizes the resuse value of your workflow for non-tag pushes.
+as it maximizes the reuse value of your workflow for non-tag pushes.
```
Remove stutter of "can can":
```diff
-You can can configure a number of options for your
+You can configure a number of options for your
```
Capitalize 'Docker':
```diff
-> **⚠️ Note:** This action was previously implemented as a docker container, limiting its use to GitHub Actions Linux virtual environments only. With recent releases, we now support cross platform usage. You'll need to remove the `docker://` prefix in these versions
+> **⚠️ Note:** This action …
```
=> Docs: Fix spelling mistakes

package-lock.json, package.json, src/main.ts
In attempt to fix unintentional retries on 422 error from GitHub,
1. Update to latest `@octokit/plugin-throttling` version
2. Depend on `@octokit/plugin-retry` plugin as well
Issue: #52
----
I found it hard to find any other way to fix the original issue, so decided to update to latest throttling plugin (with updating config key) & include retry plugin as well.
My findings based on https://github.com/probot/probot/commit/1a19bdd16cd3bf1385a8f33cab52728ef3e0ac27
If this is not expected solution for original issue, I'll need a help in fixing it.
Thanks
=> fix: Update to latest throttling plugin

__tests__/util.test.ts, src/util.ts
Fixes #71: Get the same behavior described in Docs
Now trying read `body path` first then falling back on `body`
Also fixes the wrong test unit
=> Fixes #71: Get the same behavior described in Docs

README.md, action.yml, src/main.ts
Forwarding `upload_url` of a release to the actions output so it can be used by other actions that want to upload assets.
=> Add upload_url as action output

src/github.ts
Limits the number of retries in the `release` action.
Fixes: #112
=> Limit the number of retries

CHANGELOG.md, package.json
it's been to long.  since the last release. this one's a catch up to cover a changelog of everything merged since the last release. after this I hope to make a fast follow 0.1.7 to capture everything in the pull queue and then after try to cut a release after every notable pull afterwards
=> release prep for 0.1.6

README.md, action.yml, src/util.ts
99 times out of 100 people won't need anything other than the default token already available in scope, defaulting to it saves everybody YAML setup mess.
=> Set default token for simpler setup

README.md
Replace ${{ github.workflow }} in readme.md by ${{github.workspace}}. #101 
Changelog.txt is repository specific file, not workflow specific...
=> Fix invalid ${{ github.workflow }} in readme.md

README.md
I attempted to implement this action and was stymied by the following error:
> Unexpected error fetching GitHub release for tag refs/tags/1.14.0: HttpError: Resource not accessible by integration
Our org had Actions repo access set to read-only. Even knowing that, it wasn't clear what permissions were required to actually fix the actions. Experiments reveal probably just `contents: write`. I'm a little surprised, I would have expected `packages: write` as well?
Downstream issue where we encountered this problem: https://github.com/acquia/cli/pull/654
Previous issue, where this should have been documented more visibly: https://github.com/softprops/action-gh-release/issues/96
=> Specify required permissions in README

README.md
Hi,
Thanks for such a helpful tool. I want to suggest updating the version of `actions/checkout@v2` to `actions/checkout@v3` since GitHub is moving away from node12 to node16 (https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
Cheers!
=> README: update of the `actions/checkout` to `v3`

action.yml
Fixes #404 updating the action to use `node20`
=> Update node version to node20

.github/workflows/main.yml, README.md
This PR bumps `checkout` action to latest version (in `README.md` + workflow `main.yml`).
=> Bump checkout action to latest version

src/main.ts
When the input `input_files` is not defined, the `config.input_files` will default to an empty array, which always evaluate to true - that was triggering a misleading warning suggesting that the user did input something but the input didn't point to any file.
As a fix, simply check if the array is empty as well :)
=> Do not raise misleading warning

README.md
Third-person singular simple present form of "let" is obviously intended, judging from grammatical context.
Contraction of "let us" is erroneously used instead.
=> "Let's" → "lets".

src/main.ts
- Change 'pattern does not match any files' warning to fatal
- Also raise a fatal error if the config file is not valid
Closes #383
=> Don't swallow errors

CHANGELOG.md, src/main.ts
addresses https://github.com/softprops/action-gh-release/issues/416
=> make pattern error opt in

README.md, action.yml
=> declare an update docs for make_latest input

src/github.ts
According to [this issue comment](https://github.com/softprops/action-gh-release/issues/159#issuecomment-949582196), GitHub will rename the asset, which causes the name-based check to fail for file names containing spaces. We can change the file name to the same as GitHub before checking to solve this problem.
=> fix: support space in file name

src/github.ts
- refactored the big `if/else` to exit early
- added error handling for different errors while creating a release
=> Fix: error handling

__tests__/github.test.ts, src/github.ts
Previously all assets were being read synchronously into memory, making the action unsuitable for releasing very large assets. Because the client library allows stream body inputs (it just forwards it to the underlying `fetch` implementation), just do it.
Fixes: #353
=> feat: read the release assets asynchronously

action.yml
Similar to #544 but for input description in `action.yml`.
=> fix(docs): clarify the default for tag_name
